// Complete static translations — FR / AR / EN
// No API needed — instant switching, works offline forever

const cache = {};

export function t(lang, key) {
  if (!lang || lang === 'fr') return translations.fr[key] ?? key;
  const val = translations[lang]?.[key];
  if (val !== undefined) return val;
  return translations.fr[key] ?? key;
}

export function getDir(lang) {
  return lang === 'ar' ? 'rtl' : 'ltr';
}

export const translations = {
  fr: {
    dir: 'ltr', lang: 'fr', flag: '🇫🇷', name: 'Français',
    app_name: 'Suivi Récitation',
    login_title: 'Suivi Récitation',
    login_subtitle: 'Espace instituteurs & surveillance',
    identifiant: 'Identifiant',
    mot_de_passe: 'Mot de passe',
    se_connecter: 'Se connecter',
    connexion_en_cours: 'Connexion...',
    identifiant_incorrect: 'Identifiant ou mot de passe incorrect.',
    remplir_champs: 'Veuillez remplir tous les champs.',
    role_surveillant: 'Surveillant',
    role_instituteur: 'Instituteur',
    acces_complet: 'Accès complet',
    validation_suivi: 'Validation + suivi',
    express: 'Express',
    seance: 'Séance',
    calendrier: 'Calendrier',
    rapport: 'Rapport',
    gestion: 'Gestion',
    deconnexion: 'Déconnexion',
    honneur: 'Honneur',
    comparer: 'Comparer',
    tableau_de_bord: 'Tableau de bord',
    vue_generale: 'Vue générale',
    eleves: 'Élèves',
    instituteurs: 'Instituteurs',
    rapport_tab: 'Rapport',
    score_ecole: "Score global de l'école",
    points_cumules: 'points cumulés',
    tomon_recites: 'Tomon récités',
    hizb_complets: 'Hizb complets',
    tomon_semaine: 'Tomon cette semaine',
    hizb_ce_mois: 'Hizb ce mois',
    attente_hizb: 'Attente Hizb complet',
    inactifs: 'Inactifs +14j',
    podium: 'Podium',
    a_relancer: 'À relancer',
    tous_actifs: 'Tous actifs ✓',
    aucun_attente: 'Aucun en attente ✓',
    activite_recente: 'Activité récente',
    aucune_activite: 'Aucune activité.',
    valider: 'Valider',
    classement: 'Classement',
    score_groupe: 'Score du groupe',
    meilleur_eleve: 'Meilleur élève ⭐',
    alertes: 'Alertes intelligentes',
    eleve: 'Élève',
    niveau: 'Niveau',
    referent: 'Instituteur référent',
    acquis_anterieurs: 'Acquis antérieurs',
    hizb_depart: 'Hizb de départ',
    tomon_depart: 'Tomon de départ',
    inscrit_le: 'Inscrit le',
    position_actuelle: 'Position actuelle',
    hizb_en_cours: 'Hizb en cours',
    tomon_valides: 'Tomon validés',
    prochain: 'Prochain',
    statut: 'Statut',
    actif: 'Actif',
    inactif: 'Inactif',
    jamais: 'Jamais',
    derniere_recitation: 'Dernière récitation',
    badges: 'Badges obtenus',
    objectif_mensuel: 'Objectif mensuel',
    definir: 'Définir',
    annuler: 'Annuler',
    enregistrer: 'Enregistrer',
    objectif_atteint: '🎉 Objectif atteint !',
    aucun_objectif: 'Aucun objectif fixé',
    apercu: 'Aperçu',
    apprentissage: 'Apprentissage',
    evolution: 'Évolution',
    activite: 'Activité',
    historique: 'Historique',
    retour: '← Retour',
    imprimer_pdf: '🖨️ PDF',
    enregistrer_recitation: '+ Récitation',
    voir_fiche: 'Voir la fiche',
    retour_dashboard: 'Retour au tableau de bord',
    enregistrer_recitation_titre: 'Enregistrer une récitation',
    selectionner_eleve: "Sélectionner l'élève",
    rechercher_eleve: 'Rechercher un élève...',
    changer: 'Changer',
    tomon_recites_aujourd_hui: "Tomon récités aujourd'hui",
    valider_hizb_complet: 'Valider le Hizb complet',
    bonus_pts: '+100 pts bonus',
    deja_valide: 'Déjà validé',
    recite_aujourd_hui: "Récité aujourd'hui",
    a_venir: 'À venir',
    position_atteinte: 'Position atteinte →',
    continuer: 'Continuer',
    confirmer: '✓ Confirmer la validation',
    modifier: '← Modifier',
    recapitulatif: 'Récapitulatif',
    tomon_recites_label: 'Tomon récités',
    points_gagnes: 'Points gagnés',
    valide_par: 'Validé par',
    date_heure: 'Date & heure',
    hizb_suivant_ouvre: "Hizb suivant s'ouvre",
    nouvelle_recitation: '+ Nouvelle récitation',
    enregistrement: 'Enregistrement...',
    recitation_enregistree: 'Récitation enregistrée !',
    hizb_valide_titre: 'Hizb complet validé !',
    durees_apprentissage: "Durées d'apprentissage",
    ajouter_eleve: 'Ajouter un élève',
    modifier_eleve: "Modifier l'élève",
    eleves_inscrits: 'Élèves inscrits',
    ajouter_instituteur: 'Ajouter un instituteur',
    instituteurs_actifs: 'Instituteurs actifs',
    prenom: 'Prénom',
    nom_label: 'Nom',
    identifiant_label: 'Identifiant',
    ajouter_eleve_btn: "+ Ajouter l'élève",
    ajouter_instituteur_btn: "+ Ajouter l'instituteur",
    modifier_btn: 'Modifier',
    retirer: 'Retirer',
    enregistrer_modifications: 'Enregistrer les modifications',
    acquis_aide: 'Position dans le Coran avant de commencer le suivi',
    hizb_1_60: 'Hizb (1-60)',
    tomon_1_8: 'Tomon (1-8)',
    debutant: 'Débutant',
    intermediaire: 'Intermédiaire',
    avance: 'Avancé',
    choisir: '— Choisir —',
    eleve_ajoute: 'Élève ajouté avec succès.',
    eleve_modifie: 'Élève modifié avec succès.',
    eleve_retire: 'Élève retiré.',
    instituteur_ajoute: 'Instituteur ajouté avec succès.',
    instituteur_retire: 'Instituteur retiré.',
    erreur_ajout: "Erreur lors de l'ajout.",
    prenom_nom_obligatoires: 'Prénom et nom obligatoires.',
    tous_champs_obligatoires: 'Tous les champs sont obligatoires.',
    identifiant_utilise: 'Identifiant déjà utilisé.',
    supprimer_eleve_confirm: "Supprimer cet élève et tout son historique ?",
    supprimer_instituteur_confirm: "Supprimer cet instituteur ?",
    ma_seance: 'Ma séance du jour',
    cette_semaine: 'Cette semaine',
    eleves_vus: 'Élèves vus',
    tomon_valides_label: 'Tomon validés',
    hizb_complets_label: 'Hizb complets',
    pts_generes: 'Points générés',
    classement_seance: 'Classement de la séance',
    detail_validations: 'Détail des validations',
    a_voir_aujourd_hui: "À voir aujourd'hui",
    classement_semaine: 'Classement de la semaine',
    activite_par_jour: 'Activité par jour',
    rapport_mensuel: 'Rapport mensuel',
    imprimer_rapport: '🖨️ Imprimer rapport PDF',
    performance_objectifs: 'Performance et objectifs',
    performance_instituteurs: 'Performance par instituteur',
    objectif_label: 'Objectif',
    atteinte: 'Atteinte',
    score_mois: 'Score mois',
    aucun_instituteur: 'Aucun instituteur.',
    aucun_eleve: 'Aucun élève.',
    tableau_honneur: "Tableau d'honneur",
    gardiens_coran: 'Les Gardiens du Coran',
    classement_score: 'Classement par score de récitation',
    validation_express: '⚡ Validation Express',
    validation_express_aide: 'Recherchez un élève et validez en 2 clics',
    rechercher: 'Rechercher...',
    combien_tomon: 'Combien de Tomon récités ?',
    log_session: 'Log de la session',
    rechercher_commencer: 'Recherchez un élève pour commencer',
    suivi_apprentissage: 'Suivi début → validation par Tomon',
    debut_apprentissage: 'Début apprentissage',
    validation_label: 'Validation',
    duree: 'Durée',
    en_cours: 'En cours',
    duree_moy: 'Durée moy.',
    plus_rapide: 'Plus rapide',
    plus_long: 'Plus long',
    aucun_suivi: 'Aucun suivi enregistré.',
    activite_90: 'Activité — 90 derniers jours',
    faible: 'Faible',
    fort: 'Fort',
    streak_actuel: 'Streak actuel',
    jours_actifs: 'Jours actifs',
    moy_seance: 'Moy/séance',
    score_total: 'Score total',
    pts_abrev: 'pts',
    hizb_abrev: 'Hizb',
    tomon_abrev: 'Tomon',
    hizb_complets_abrev: 'Hizb complets',
    actifs: 'Actifs',
    inactifs_filter: 'Inactifs',
    attente_filter: 'Attente Hizb',
    tous: 'Tous',
    tous_instituteurs: 'Tous les instituteurs',
    tous_statuts: 'Tous les statuts',
    tous_niveaux: 'Tous les niveaux',
    tri_score_desc: 'Score ↓',
    tri_score_asc: 'Score ↑',
    tri_hizb_desc: 'Hizb ↓',
    tri_hizb_asc: 'Hizb ↑',
    tri_nom: 'Nom A→Z',
    tri_recente: 'Récente',
    tri_inactif: 'Inactifs',
    eleves_referents: 'élèves référents',
    voir_profil: 'Voir profil →',
    pas_assez_donnees: 'Pas encore assez de données.',
    aucune_recitation_label: 'Aucune récitation.',
    en_attente: 'En attente',
    jour: 'j',
    jours: 'j',
    classement_complet: 'Classement complet',
    eleves_actifs: 'Élèves actifs',
    recitations_ce_mois: 'Récitations ce mois',
    nb_seances: 'Séances',
    comparer_eleves: 'Comparaison des élèves',
    selectionner_comparer: "Sélectionnez jusqu'à 6 élèves",
    evolution_score: 'Évolution du score',
    tableau_comparatif: 'Tableau comparatif',
    classement_entre_eux: 'Classement entre eux',
    detail: 'Détail',
    duree_apprentissage_col: 'Durée appr.',
    debut_suivi: 'Début du suivi',
    total_recitations: 'Total récitations',
    progression_hizb: 'Progression Hizb',
    validation_hizb_requise: 'Validation Hizb complet requise.',
    hizb_complet_a_valider: 'Hizb complet à valider',
    score_mois_label: 'Score ce mois',
    genere_le: 'Généré le',
    aucune_recitation: 'Aucune récitation ce jour.',
    prochain_tomon: 'prochain',
    jours_label: 'jours',
    semaines: 'sem.',
  },

  ar: {
    dir: 'rtl', lang: 'ar', flag: '🇸🇦', name: 'العربية',
    app_name: 'متابعة التحفيظ',
    login_title: 'متابعة التحفيظ',
    login_subtitle: 'فضاء الأساتذة والمراقب العام',
    identifiant: 'المعرّف',
    mot_de_passe: 'كلمة السر',
    se_connecter: 'تسجيل الدخول',
    connexion_en_cours: 'جارٍ الدخول...',
    identifiant_incorrect: 'المعرّف أو كلمة السر غير صحيحة.',
    remplir_champs: 'يرجى ملء جميع الحقول.',
    role_surveillant: 'المراقب العام',
    role_instituteur: 'الأستاذ',
    acces_complet: 'صلاحية كاملة',
    validation_suivi: 'تصحيح ومتابعة',
    express: 'سريع',
    seance: 'الحصة',
    calendrier: 'التقويم',
    rapport: 'التقرير',
    gestion: 'الإدارة',
    deconnexion: 'خروج',
    honneur: 'لوح الشرف',
    comparer: 'مقارنة',
    tableau_de_bord: 'لوحة القيادة',
    vue_generale: 'النظرة العامة',
    eleves: 'الطلاب',
    instituteurs: 'الأساتذة',
    rapport_tab: 'التقرير',
    score_ecole: 'المجموع العام للمدرسة',
    points_cumules: 'نقطة مجموعة',
    tomon_recites: 'ثُمن مُسمَّع',
    hizb_complets: 'أحزاب مكتملة',
    tomon_semaine: 'ثُمن هذا الأسبوع',
    hizb_ce_mois: 'أحزاب هذا الشهر',
    attente_hizb: 'انتظار تصحيح الحزب',
    inactifs: 'غير نشطين +14 يوم',
    podium: 'منصة التتويج',
    a_relancer: 'يجب التواصل معهم',
    tous_actifs: 'جميعهم نشطون ✓',
    aucun_attente: 'لا أحد في الانتظار ✓',
    activite_recente: 'النشاط الأخير',
    aucune_activite: 'لا يوجد نشاط.',
    valider: 'تصحيح',
    classement: 'الترتيب',
    score_groupe: 'مجموع المجموعة',
    meilleur_eleve: 'أفضل طالب ⭐',
    alertes: 'تنبيهات ذكية',
    eleve: 'الطالب',
    niveau: 'المستوى',
    referent: 'الأستاذ المرجع',
    acquis_anterieurs: 'المكتسبات السابقة',
    hizb_depart: 'الحزب الابتدائي',
    tomon_depart: 'الثُّمن الابتدائي',
    inscrit_le: 'تاريخ التسجيل',
    position_actuelle: 'الموقع الحالي',
    hizb_en_cours: 'الحزب الحالي',
    tomon_valides: 'الثُّمن المصحَّح',
    prochain: 'التالي',
    statut: 'الحالة',
    actif: 'نشط',
    inactif: 'غير نشط',
    jamais: 'لم يُسمِّع بعد',
    derniere_recitation: 'آخر استظهار',
    badges: 'الأوسمة',
    objectif_mensuel: 'الهدف الشهري',
    definir: 'تحديد',
    annuler: 'إلغاء',
    enregistrer: 'حفظ',
    objectif_atteint: '🎉 تم تحقيق الهدف!',
    aucun_objectif: 'لم يُحدَّد هدف',
    apercu: 'لمحة عامة',
    apprentissage: 'الحفظ',
    evolution: 'التطور',
    activite: 'النشاط',
    historique: 'السجل',
    retour: 'رجوع →',
    imprimer_pdf: '🖨️ طباعة',
    enregistrer_recitation: '+ استظهار',
    voir_fiche: 'عرض الملف',
    retour_dashboard: 'العودة للوحة القيادة',
    enregistrer_recitation_titre: 'تسجيل استظهار',
    selectionner_eleve: 'اختيار الطالب',
    rechercher_eleve: 'البحث عن طالب...',
    changer: 'تغيير',
    tomon_recites_aujourd_hui: 'الثُّمن المُسمَّع اليوم',
    valider_hizb_complet: 'تصحيح الحزب كاملاً',
    bonus_pts: '+100 نقطة إضافية',
    deja_valide: 'مُصحَّح',
    recite_aujourd_hui: 'مُسمَّع اليوم',
    a_venir: 'قادم',
    position_atteinte: 'الموقع المُحقَّق →',
    continuer: 'متابعة',
    confirmer: '✓ تأكيد التصحيح',
    modifier: 'تعديل →',
    recapitulatif: 'ملخص',
    tomon_recites_label: 'الثُّمن المُسمَّع',
    points_gagnes: 'النقاط المكتسبة',
    valide_par: 'صحَّحه',
    date_heure: 'التاريخ والوقت',
    hizb_suivant_ouvre: 'الحزب التالي مفتوح',
    nouvelle_recitation: '+ استظهار جديد',
    enregistrement: 'جارٍ الحفظ...',
    recitation_enregistree: 'تم تسجيل الاستظهار!',
    hizb_valide_titre: 'تم تصحيح الحزب كاملاً!',
    durees_apprentissage: 'مدة الحفظ',
    ajouter_eleve: 'إضافة طالب',
    modifier_eleve: 'تعديل بيانات الطالب',
    eleves_inscrits: 'الطلاب المسجلون',
    ajouter_instituteur: 'إضافة أستاذ',
    instituteurs_actifs: 'الأساتذة النشطون',
    prenom: 'الاسم',
    nom_label: 'اللقب',
    identifiant_label: 'المعرّف',
    ajouter_eleve_btn: '+ إضافة الطالب',
    ajouter_instituteur_btn: '+ إضافة الأستاذ',
    modifier_btn: 'تعديل',
    retirer: 'حذف',
    enregistrer_modifications: 'حفظ التعديلات',
    acquis_aide: 'موقع الطالب في القرآن قبل بدء المتابعة',
    hizb_1_60: 'الحزب (1-60)',
    tomon_1_8: 'الثُّمن (1-8)',
    debutant: 'مبتدئ',
    intermediaire: 'متوسط',
    avance: 'متقدم',
    choisir: '— اختيار —',
    eleve_ajoute: 'تم إضافة الطالب بنجاح.',
    eleve_modifie: 'تم تعديل بيانات الطالب بنجاح.',
    eleve_retire: 'تم حذف الطالب.',
    instituteur_ajoute: 'تم إضافة الأستاذ بنجاح.',
    instituteur_retire: 'تم حذف الأستاذ.',
    erreur_ajout: 'حدث خطأ أثناء الإضافة.',
    prenom_nom_obligatoires: 'الاسم واللقب إلزاميان.',
    tous_champs_obligatoires: 'جميع الحقول إلزامية.',
    identifiant_utilise: 'هذا المعرّف مستخدم مسبقاً.',
    supprimer_eleve_confirm: 'حذف هذا الطالب وكل سجله؟',
    supprimer_instituteur_confirm: 'حذف هذا الأستاذ؟',
    ma_seance: 'حصتي اليوم',
    cette_semaine: 'هذا الأسبوع',
    eleves_vus: 'طلاب تمت متابعتهم',
    tomon_valides_label: 'ثُمن مُصحَّح',
    hizb_complets_label: 'حزب مكتمل',
    pts_generes: 'نقاط مكتسبة',
    classement_seance: 'ترتيب الحصة',
    detail_validations: 'تفاصيل الاستظهارات',
    a_voir_aujourd_hui: 'للمتابعة اليوم',
    classement_semaine: 'ترتيب الأسبوع',
    activite_par_jour: 'النشاط اليومي',
    rapport_mensuel: 'التقرير الشهري',
    imprimer_rapport: '🖨️ طباعة التقرير',
    performance_objectifs: 'الأداء والأهداف',
    performance_instituteurs: 'أداء الأساتذة',
    objectif_label: 'الهدف',
    atteinte: 'النسبة',
    score_mois: 'نقاط الشهر',
    aucun_instituteur: 'لا يوجد أساتذة.',
    aucun_eleve: 'لا يوجد طلاب.',
    tableau_honneur: 'لوح الشرف',
    gardiens_coran: 'حفّاظ القرآن الكريم',
    classement_score: 'الترتيب حسب نقاط الاستظهار',
    validation_express: '⚡ تسجيل سريع',
    validation_express_aide: 'ابحث عن طالب وسجّل استظهاره بنقرتين',
    rechercher: 'بحث...',
    combien_tomon: 'كم ثُمناً تمّ استظهاره؟',
    log_session: 'سجل الحصة',
    rechercher_commencer: 'ابحث عن طالب للبدء',
    suivi_apprentissage: 'متابعة بداية الحفظ ← الاستظهار',
    debut_apprentissage: 'بداية الحفظ',
    validation_label: 'الاستظهار',
    duree: 'المدة',
    en_cours: 'قيد الحفظ',
    duree_moy: 'متوسط المدة',
    plus_rapide: 'الأسرع',
    plus_long: 'الأطول',
    aucun_suivi: 'لا يوجد متابعة مسجلة.',
    activite_90: 'النشاط — آخر 90 يوماً',
    faible: 'ضعيف',
    fort: 'قوي',
    streak_actuel: 'الاستمرارية',
    jours_actifs: 'أيام نشطة',
    moy_seance: 'متوسط/حصة',
    score_total: 'المجموع الكلي',
    pts_abrev: 'ن',
    hizb_abrev: 'حزب',
    tomon_abrev: 'ثُمن',
    hizb_complets_abrev: 'أحزاب مكتملة',
    actifs: 'نشطون',
    inactifs_filter: 'غير نشطين',
    attente_filter: 'انتظار الحزب',
    tous: 'الكل',
    tous_instituteurs: 'جميع الأساتذة',
    tous_statuts: 'جميع الحالات',
    tous_niveaux: 'جميع المستويات',
    tri_score_desc: 'النقاط ↓',
    tri_score_asc: 'النقاط ↑',
    tri_hizb_desc: 'الحزب ↓',
    tri_hizb_asc: 'الحزب ↑',
    tri_nom: 'الاسم أ→ي',
    tri_recente: 'الأحدث',
    tri_inactif: 'غير نشطين',
    eleves_referents: 'طلاب مرجعيون',
    voir_profil: 'عرض الملف ←',
    pas_assez_donnees: 'لا توجد بيانات كافية بعد.',
    aucune_recitation_label: 'لا يوجد استظهار.',
    en_attente: 'في الانتظار',
    jour: 'ي',
    jours: 'أيام',
    classement_complet: 'الترتيب الكامل',
    eleves_actifs: 'طلاب نشطون',
    recitations_ce_mois: 'استظهارات هذا الشهر',
    nb_seances: 'الحصص',
    comparer_eleves: 'مقارنة الطلاب',
    selectionner_comparer: 'اختر حتى 6 طلاب للمقارنة',
    evolution_score: 'تطور النقاط',
    tableau_comparatif: 'جدول المقارنة',
    classement_entre_eux: 'الترتيب بينهم',
    detail: 'تفصيل',
    duree_apprentissage_col: 'مدة الحفظ',
    debut_suivi: 'بداية المتابعة',
    total_recitations: 'إجمالي الاستظهارات',
    progression_hizb: 'تقدم الحزب',
    validation_hizb_requise: 'يجب تصحيح الحزب كاملاً.',
    hizb_complet_a_valider: 'الحزب يحتاج تصحيحاً',
    score_mois_label: 'نقاط الشهر',
    genere_le: 'أُنشئ بتاريخ',
    aucune_recitation: 'لا يوجد استظهار هذا اليوم.',
    prochain_tomon: 'التالي',
    jours_label: 'يوم',
    semaines: 'أسبوع',
  },

  en: {
    dir: 'ltr', lang: 'en', flag: '🇬🇧', name: 'English',
    app_name: 'Quran Tracking',
    login_title: 'Quran Tracking',
    login_subtitle: 'Teachers & Supervisor Portal',
    identifiant: 'Username',
    mot_de_passe: 'Password',
    se_connecter: 'Sign In',
    connexion_en_cours: 'Signing in...',
    identifiant_incorrect: 'Invalid username or password.',
    remplir_champs: 'Please fill in all fields.',
    role_surveillant: 'Supervisor',
    role_instituteur: 'Teacher',
    acces_complet: 'Full access',
    validation_suivi: 'Validation & tracking',
    express: 'Express',
    seance: 'Session',
    calendrier: 'Calendar',
    rapport: 'Report',
    gestion: 'Management',
    deconnexion: 'Logout',
    honneur: 'Hall of Fame',
    comparer: 'Compare',
    tableau_de_bord: 'Dashboard',
    vue_generale: 'Overview',
    eleves: 'Students',
    instituteurs: 'Teachers',
    rapport_tab: 'Report',
    score_ecole: 'School Total Score',
    points_cumules: 'cumulated points',
    tomon_recites: 'Tomon recited',
    hizb_complets: 'Complete Hizb',
    tomon_semaine: 'Tomon this week',
    hizb_ce_mois: 'Hizb this month',
    attente_hizb: 'Awaiting Hizb validation',
    inactifs: 'Inactive +14 days',
    podium: 'Podium',
    a_relancer: 'To follow up',
    tous_actifs: 'All active ✓',
    aucun_attente: 'None waiting ✓',
    activite_recente: 'Recent activity',
    aucune_activite: 'No activity.',
    valider: 'Validate',
    classement: 'Ranking',
    score_groupe: 'Group score',
    meilleur_eleve: 'Top student ⭐',
    alertes: 'Smart alerts',
    eleve: 'Student',
    niveau: 'Level',
    referent: 'Assigned teacher',
    acquis_anterieurs: 'Prior achievements',
    hizb_depart: 'Starting Hizb',
    tomon_depart: 'Starting Tomon',
    inscrit_le: 'Enrolled on',
    position_actuelle: 'Current position',
    hizb_en_cours: 'Current Hizb',
    tomon_valides: 'Tomon validated',
    prochain: 'Next',
    statut: 'Status',
    actif: 'Active',
    inactif: 'Inactive',
    jamais: 'Never',
    derniere_recitation: 'Last recitation',
    badges: 'Badges',
    objectif_mensuel: 'Monthly goal',
    definir: 'Set goal',
    annuler: 'Cancel',
    enregistrer: 'Save',
    objectif_atteint: '🎉 Goal achieved!',
    aucun_objectif: 'No goal set',
    apercu: 'Overview',
    apprentissage: 'Learning',
    evolution: 'Progress',
    activite: 'Activity',
    historique: 'History',
    retour: '← Back',
    imprimer_pdf: '🖨️ PDF',
    enregistrer_recitation: '+ Recitation',
    voir_fiche: 'View profile',
    retour_dashboard: 'Back to dashboard',
    enregistrer_recitation_titre: 'Record a recitation',
    selectionner_eleve: 'Select student',
    rechercher_eleve: 'Search student...',
    changer: 'Change',
    tomon_recites_aujourd_hui: 'Tomon recited today',
    valider_hizb_complet: 'Validate complete Hizb',
    bonus_pts: '+100 bonus pts',
    deja_valide: 'Already validated',
    recite_aujourd_hui: 'Recited today',
    a_venir: 'Upcoming',
    position_atteinte: 'Position reached →',
    continuer: 'Continue',
    confirmer: '✓ Confirm validation',
    modifier: '← Edit',
    recapitulatif: 'Summary',
    tomon_recites_label: 'Tomon recited',
    points_gagnes: 'Points earned',
    valide_par: 'Validated by',
    date_heure: 'Date & time',
    hizb_suivant_ouvre: 'Next Hizb opens',
    nouvelle_recitation: '+ New recitation',
    enregistrement: 'Saving...',
    recitation_enregistree: 'Recitation recorded!',
    hizb_valide_titre: 'Complete Hizb validated!',
    durees_apprentissage: 'Learning durations',
    ajouter_eleve: 'Add student',
    modifier_eleve: 'Edit student',
    eleves_inscrits: 'Enrolled students',
    ajouter_instituteur: 'Add teacher',
    instituteurs_actifs: 'Active teachers',
    prenom: 'First name',
    nom_label: 'Last name',
    identifiant_label: 'Username',
    ajouter_eleve_btn: '+ Add student',
    ajouter_instituteur_btn: '+ Add teacher',
    modifier_btn: 'Edit',
    retirer: 'Remove',
    enregistrer_modifications: 'Save changes',
    acquis_aide: 'Position in the Quran before tracking begins',
    hizb_1_60: 'Hizb (1-60)',
    tomon_1_8: 'Tomon (1-8)',
    debutant: 'Beginner',
    intermediaire: 'Intermediate',
    avance: 'Advanced',
    choisir: '— Choose —',
    eleve_ajoute: 'Student added successfully.',
    eleve_modifie: 'Student updated successfully.',
    eleve_retire: 'Student removed.',
    instituteur_ajoute: 'Teacher added successfully.',
    instituteur_retire: 'Teacher removed.',
    erreur_ajout: 'Error while adding.',
    prenom_nom_obligatoires: 'First name and last name required.',
    tous_champs_obligatoires: 'All fields are required.',
    identifiant_utilise: 'Username already taken.',
    supprimer_eleve_confirm: 'Delete this student and all their records?',
    supprimer_instituteur_confirm: 'Delete this teacher?',
    ma_seance: "Today's session",
    cette_semaine: 'This week',
    eleves_vus: 'Students seen',
    tomon_valides_label: 'Tomon validated',
    hizb_complets_label: 'Complete Hizb',
    pts_generes: 'Points generated',
    classement_seance: 'Session ranking',
    detail_validations: 'Validation details',
    a_voir_aujourd_hui: 'To see today',
    classement_semaine: 'Weekly ranking',
    activite_par_jour: 'Daily activity',
    rapport_mensuel: 'Monthly report',
    imprimer_rapport: '🖨️ Print PDF report',
    performance_objectifs: 'Performance & goals',
    performance_instituteurs: 'Teacher performance',
    objectif_label: 'Goal',
    atteinte: 'Achievement',
    score_mois: 'Month score',
    aucun_instituteur: 'No teachers.',
    aucun_eleve: 'No students.',
    tableau_honneur: 'Hall of Fame',
    gardiens_coran: 'Guardians of the Quran',
    classement_score: 'Ranked by recitation score',
    validation_express: '⚡ Express Validation',
    validation_express_aide: 'Search a student and validate in 2 clicks',
    rechercher: 'Search...',
    combien_tomon: 'How many Tomon recited?',
    log_session: 'Session log',
    rechercher_commencer: 'Search a student to begin',
    suivi_apprentissage: 'Learning: start → validation per Tomon',
    debut_apprentissage: 'Learning start',
    validation_label: 'Validation',
    duree: 'Duration',
    en_cours: 'In progress',
    duree_moy: 'Avg duration',
    plus_rapide: 'Fastest',
    plus_long: 'Longest',
    aucun_suivi: 'No learning records yet.',
    activite_90: 'Activity — last 90 days',
    faible: 'Low',
    fort: 'High',
    streak_actuel: 'Current streak',
    jours_actifs: 'Active days',
    moy_seance: 'Avg/session',
    score_total: 'Total score',
    pts_abrev: 'pts',
    hizb_abrev: 'Hizb',
    tomon_abrev: 'Tomon',
    hizb_complets_abrev: 'Complete Hizb',
    actifs: 'Active',
    inactifs_filter: 'Inactive',
    attente_filter: 'Awaiting Hizb',
    tous: 'All',
    tous_instituteurs: 'All teachers',
    tous_statuts: 'All statuses',
    tous_niveaux: 'All levels',
    tri_score_desc: 'Score ↓',
    tri_score_asc: 'Score ↑',
    tri_hizb_desc: 'Hizb ↓',
    tri_hizb_asc: 'Hizb ↑',
    tri_nom: 'Name A→Z',
    tri_recente: 'Recent',
    tri_inactif: 'Inactive',
    eleves_referents: 'assigned students',
    voir_profil: 'View profile →',
    pas_assez_donnees: 'Not enough data yet.',
    aucune_recitation_label: 'No recitations.',
    en_attente: 'Waiting',
    jour: 'd',
    jours: 'days',
    classement_complet: 'Full ranking',
    eleves_actifs: 'Active students',
    recitations_ce_mois: 'Recitations this month',
    nb_seances: 'Sessions',
    comparer_eleves: 'Student comparison',
    selectionner_comparer: 'Select up to 6 students',
    evolution_score: 'Score evolution',
    tableau_comparatif: 'Comparison table',
    classement_entre_eux: 'Ranking between them',
    detail: 'Detail',
    duree_apprentissage_col: 'Learn. time',
    debut_suivi: 'Tracking start',
    total_recitations: 'Total recitations',
    progression_hizb: 'Hizb progress',
    validation_hizb_requise: 'Complete Hizb validation required.',
    hizb_complet_a_valider: 'Hizb to validate',
    score_mois_label: 'Month score',
    genere_le: 'Generated on',
    aucune_recitation: 'No recitation this day.',
    prochain_tomon: 'next',
    jours_label: 'day',
    semaines: 'wks',
  }
};
